#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
email=$(ynh_user_get_info --username="$admin" --key=mail)

timezone=$(timedatectl show --value --property=Timezone)

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression "Storing admin user settings..."

ynh_app_setting_set --key=email --value="$email"

#=================================================
# CONFIGURE REDIS DATABASE
#=================================================
ynh_script_progression "Creating a Redis database..."

redis_db=$(ynh_redis_get_free_db)

ynh_app_setting_set --key=redis_db --value="$redis_db"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod -R g+w "$install_dir/storage"
chown -R "$app:www-data" "$install_dir/storage"

#=================================================
# ADD APP ENV FILE
#=================================================
ynh_config_add --template="env.example" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

#touch "/var/log/$app/$app.log"
#chmod 660 "/var/log/$app/$app.log"
#chown "$app:www-data" "/var/log/$app/$app.log"

#=================================================
# INSTALL APP
#=================================================
#ynh_script_progression "Install $app..."

pushd "$install_dir"
	ynh_exec_as_app "php$php_version" artisan key:generate -n --force
 	ynh_exec_as_app "php$php_version" artisan migrate -n --force
#    ynh_exec_as_app "php$php_version" artisan setup:complete -n
#    ynh_exec_as_app "php$php_version" artisan --admin registeruser "$admin" "$email"
popd

#=================================================
# ADD A CRON JOB
#=================================================
ynh_config_add --template="linkace.cron" --destination="/etc/cron.d/$app"
chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation complete."
