#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations..."

ynh_config_remove_nginx

ynh_config_remove_phpfpm

ynh_config_remove_logrotate

ynh_redis_remove_db "$redis_db"

ynh_safe_rm "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal complete."
