#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chmod -R g+w "$install_dir/storage"
chown -R "$app:www-data" "$install_dir/storage"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_logrotate

#=================================================
# STORE THE CONFIG FILE CHECKSUM
#=================================================
pushd "$install_dir"
	ynh_exec_as_app "php$php_version" artisan key:generate -n --force
 	ynh_exec_as_app "php$php_version" artisan migrate -n --force
popd

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Upgrade of $app completed"
